enum SortByBattingField {
    BATTING_AVERAGE = 1, STRIKE_RATE, MAXIMUM_FOURS_SIXES, STRIKE_RATE_AND_MAX_FOURS_SIXES, 
    STRIKE_RATE_AND_BATTING_AVERAGE, BATTING_AVERAGE_AND_MAXIMUM_RUNS, BATTING_AVERAGE_AND_MAXIMUM_HUNDERDS, 
    ZERO_HALF_CENTURIES_AND_ZERO_CENTURIES_MAXIMUM_BATTING_AVERAGE, QUIT
};