enum SortType {
    BATTING_AVERAGE1 = 1, STRIKE_RATE1, MAXIMUM_FOURS_SIXES1, STRIKE_RATE_AND_MAX_FOURS_SIXES1, 
    STRIKE_RATE_AND_BATTING_AVERAGE1, BATTING_AVERAGE_AND_MAXIMUM_RUNS1, BATTING_AVERAGE_AND_MAXIMUM_HUNDERDS1, 
    ZERO_HALF_CENTURIES_AND_ZERO_CENTURIES_MAXIMUM_BATTING_AVERAGE1, BOWLING_AVERAGE1, STRIKING_RATE1, ECONOMY_RATE1, STRIKING_RATE_WITH_4WKTS_5WKTS1,
    STRIKING_RATE_AND_BOWLING_AVERAGE1, BOWLING_AVERAGE_AND_MAXIMUM_WICKETS1, QUIT1
};