enum SortType {
    BATTING_AVERAGE = 1, STRIKE_RATE, MAXIMUM_FOURS_SIXES, STRIKE_RATE_AND_MAX_FOURS_SIXES, 
    STRIKE_RATE_AND_BATTING_AVERAGE, BATTING_AVERAGE_AND_MAXIMUM_RUNS, BATTING_AVERAGE_AND_MAXIMUM_HUNDERDS, 
    ZERO_HALF_CENTURIES_AND_ZERO_CENTURIES_MAXIMUM_BATTING_AVERAGE, BOWLING_AVERAGE, STRIKING_RATE, ECONOMY_RATE, STRIKING_RATE_WITH_4WKTS_5WKTS,
    STRIKING_RATE_AND_BOWLING_AVERAGE, BOWLING_AVERAGE_AND_MAXIMUM_WICKETS, QUIT
};